### ISSUE TITLE
Create migration table for `carbon-icons`

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon-elements#217]
This migration for v10 will most likely be grouped in the following ways:

- For consumers of `carbon-icons` directly
- For transient consumers through `carbon-components-react`

This issue will be for creating the migration docs for the first group. This means we will need to provide:

- A list of components in v7 of `carbon-icons`
- A list of their status in Carbon v10, which would correspond to `@carbon/icons`, this can be one of:
  - New
  - Changed, should note what has changed
  - Deprecated, should note alternative
  - Removed, should note alternative (if one exists)

The latest spreadsheet for icons and their statuses is available [here](https://ibm.box.com/s/qtw8lhd3rlk89gk7x34xphjw6y077dk5)

**Comment by joshblack** [comment]
@aagonzales let me know if you need any help here! 😄

**Comment by aagonzales** [comment]
🤦‍♂️ Just haven't gotten to it yet ...

**Comment by aagonzales** [comment]
Migration doc is here: https://ibm.box.com/s/4bf8ziud70k1gg77y2olljqhb62s95cd

**Comment by joshblack** [comment]
Re-opening this, cc @chrisconnors-ibm to verify shared above ☝️
