### ISSUE TITLE
Pictogram library support

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon-elements#426]
In our icon migration guide, we currently are specifying icons that should be considered pictograms and moved over to the pictogram package.

This issue is for design to identify which icons should be moved to the pictogram package and list them as a comment in this issue.

**Comment by chrisconnors-ibm** [comment]
@conradennis  are there Pictograms currently in the `svg/32/` directory? My understanding was that pictograms are typically larger than 32x32

**Comment by aagonzales** [comment]
I think Pictograms should live separately than the ui icons. They serve different purposes and its not a 1:1 correlation between pictograms and ui icons. I can work on making a list next week, but you might need to rope in Pete, Shixie or Lauren if its a priority for this week.

**Comment by chrisconnors-ibm** [comment]
@conradennis - can you identify if any assets in 32/ are considered pictograms? or are `pictograms` by definition > 32x32?

@aagonzales 
>I think Pictograms should live separately than the ui icons. They serve different purposes and its not a 1:1 correlation between pictograms and ui icons; they have different sizes and style guidelines.

100% agree - should they be in a separate directory in the `icons` package
`carbon-elements/packages/icons/src/svg/pictograms/` 

…or a separate package `carbon-elements/packages/pictograms/`? 

@joshblack are there any implications that favor or eliminate either of those approaches?

**Comment by conradennis** [comment]
There are currently no individual SVGs of pictograms and there are definitely no pictos in the UI icon repo. Agree with @aagonzales that pictos should live separately from UI icons though I think we still consider them part of iconography as a whole. It may be simpler to put them into a separate package since they call for diff styling/treatment and are not as similar as UI and app icons.
