### ISSUE TITLE
Contribution: Mini chevron icon

### ISSUE THREAD

**Issue by m-battelli** [carbon-design-system/carbon-elements#491]
**Is your feature request related to a problem? Please describe.**
The usage of dropdown interaction for an icon button (Color text & text alignment) in the Text toolbar #361 

**AS-IS (Design playback on March 29):**
<img width="1193" alt="Screen Shot 2019-04-16 at 16 12 33" src="https://user-images.githubusercontent.com/47557215/56217016-c6ce9680-6062-11e9-8d16-ee1bf7d16881.png">

**Describe the solution you'd like**
After feedback received during the playback I have designed a mini chevron icon that fits perfectly into the button respecting the redlines.

All files here: https://ibm.box.com/s/3nrio49so9yw8ljfaex7x6m2uf95lfn3

**Screenshot details:**
<img width="680" alt="Screen Shot 2019-04-16 at 16 08 25" src="https://user-images.githubusercontent.com/47557215/56216538-e6b18a80-6061-11e9-92bf-04cf2b4f3ac3.png">

**TO-BE:**
<img width="1217" alt="Screen Shot 2019-04-16 at 16 09 33" src="https://user-images.githubusercontent.com/47557215/56216629-12347500-6062-11e9-8a2c-10dcc77931bb.png">

**The size of this new icon is 8 px.**

**Comment by joshblack** [comment]
cc @chrisconnors-ibm

**Comment by chrisconnors-ibm** [comment]
let's confirm that the pattern above is the resolution here.

We will make this as a 16x16 and your developers will pare it down to this size though - we're moving away from oddly sized 'glyphs'.

**Comment by m-battelli** [comment]
@chrisconnors-ibm 

I have updated the icon size as you suggested.
All files are here: https://ibm.box.com/s/3nrio49so9yw8ljfaex7x6m2uf95lfn3

**Comment by m-battelli** [comment]
@chrisconnors-ibm 
All files are here: https://ibm.box.com/s/9qrio6rnjs48bovf8pum92t27fyyf1ct

**Comment by chrisconnors-ibm** [comment]
there's tons of stuff on the svg that shouldn't be there. (extra artboards and labels and stuff hidden but present.)

I wasn't clear about this, but _art_ should be the original proposed dimensions (6x6) on a 16 by 16 artboard. @joshblack might have some thoughts about where to place it on the artboard (centered vs lower right)

**Comment by m-battelli** [comment]
@chrisconnors-ibm 
I have created a new AI file to avoid the “ghost” artboards.
I have placed the 6x6 icon on lower right corner.
The files are here: https://ibm.box.com/s/ztqr2h7tmsye8l3ds6dnbqhxmklafbfz

Let me know if this link works, thank you!
