### ISSUE TITLE
SVG icons don't show up in IE 11

### ISSUE THREAD

**Issue by dsuwirya** [carbon-design-system/carbon-elements#519]
Hello,

I've been using this for my project: https://github.com/carbon-design-system/carbon-elements/tree/master/packages/icons-angular.

But in IE 11, none of the icon is getting displayed. When inspected, the <path> is not getting rendered.

Thanks.

**Comment by joshblack** [comment]
Hi there! This project has been moved over to:
https://github.com/carbon-design-system/carbon

Any issues made in this project should be migrated over to that location.

**Comment by dsuwirya** [comment]
Ahhh ... thanks for letting me know.

I created a new issue there: https://github.com/carbon-design-system/carbon/issues/2826

Thanks.
